//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela CARROS
    /// </summary>
    public partial interface ICarros : IEntityBase
    {
        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<bool> Ativo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Identificador (IDENTIFICADOR.)
        /// Opcional = N, Invisível = False, Tamanho = 12
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Identificador
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IModelosCarros ModeloInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle ModeloHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Observações (OBSERVACOES.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Observacoes
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela CARROS
    /// </summary>
    public partial interface ICarrosDao : IBusinessEntityDao<ICarros>
    {
    }
    
    /// <summary>
    /// DAO para a tabela CARROS
    /// </summary>
    public partial class CarrosDao : BusinessEntityDao<Carros, ICarros>, ICarrosDao
    {
        
        public static CarrosDao CreateInstance()
        {
            return CreateInstance<CarrosDao>();
        }
    }
    
    /// <summary>
    /// Carros
    /// </summary>
    [EntityDefinitionName("CARROS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Carros : BusinessEntity<Carros>, ICarros
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Ativo = "ATIVO";
			public const string Identificador = "IDENTIFICADOR";
			public const string Modelo = "MODELO";
			public const string Observacoes = "OBSERVACOES";
		}

        
        /// <summary>
        /// Ativo (ATIVO.)
        /// Opcional = N, Invisível = False, Default = True
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<bool> Ativo
        {
            get
            {
                return Fields["ATIVO"] as System.Nullable<System.Boolean>;
            }
            set
            {
                Fields["ATIVO"] = value;
            }
        }
        
        /// <summary>
        /// Identificador (IDENTIFICADOR.)
        /// Opcional = N, Invisível = False, Tamanho = 12
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Identificador
        {
            get
            {
                return Fields["IDENTIFICADOR"] as System.String;
            }
            set
            {
                Fields["IDENTIFICADOR"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IModelosCarros ModeloInstance
        {
            get
            {
                if (Modelo.Handle == null)
                {
					return null;
                }
                return Modelo.Instance;
            }
            set
            {
                if (value == null)
                {
					Modelo = null;
					return;
                }
                Modelo.Instance = (Benner.Reservas.Entidades.ModelosCarros) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle ModeloHandle
        {
            get
            {
                return Modelo.Handle;
            }
            set
            {
                Modelo.Handle = value;
            }
        }
        
        /// <summary>
        /// Modelo (MODELO.)
        /// Opcional = N, Invisível = False, Pesquisar = MODELOSCARROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.ModelosCarros> Modelo
        {
            get
            {
                return (Fields["MODELO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.ModelosCarros>(Benner.Reservas.Entidades.ModelosCarros.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Modelo.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Modelo.Instance = value.Instance;
                    }
                    else
                    {
                        this.Modelo.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Observações (OBSERVACOES.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Observacoes
        {
            get
            {
                return Fields["OBSERVACOES"] as System.String;
            }
            set
            {
                Fields["OBSERVACOES"] = value;
            }
        }
    }
}
