//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela DOCUMENTOSFINANCEIROS
    /// </summary>
    public partial interface IDocumentosFinanceiros : IEntityBase
    {
        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        DocumentosFinanceirosTipoListaItens Tipo
        {
            get;
            set;
        }
        
        /// <summary>
        /// Valor (VALOR.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<decimal> Valor
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela DOCUMENTOSFINANCEIROS
    /// </summary>
    public partial interface IDocumentosFinanceirosDao : IBusinessEntityDao<IDocumentosFinanceiros>
    {
    }
    
    /// <summary>
    /// DAO para a tabela DOCUMENTOSFINANCEIROS
    /// </summary>
    public partial class DocumentosFinanceirosDao : BusinessEntityDao<DocumentosFinanceiros, IDocumentosFinanceiros>, IDocumentosFinanceirosDao
    {
        
        public static DocumentosFinanceirosDao CreateInstance()
        {
            return CreateInstance<DocumentosFinanceirosDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo TIPO.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
    public class DocumentosFinanceirosTipoListaItens : ListItems<DocumentosFinanceirosTipoListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Crédito.
        /// </summary>
        public static DocumentosFinanceirosTipoListaItens ItemCredito;
        
        /// <summary>
        /// Valor = 2, Item = Débito.
        /// </summary>
        public static DocumentosFinanceirosTipoListaItens ItemDebito;
        
		public static implicit operator DocumentosFinanceirosTipoListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(DocumentosFinanceirosTipoListaItens item)
		{
			return item.Index;
		}
        
        static DocumentosFinanceirosTipoListaItens()
        {
			ItemCredito = new DocumentosFinanceirosTipoListaItens {Index = 1, Description ="Crédito"};
			ItemDebito = new DocumentosFinanceirosTipoListaItens {Index = 2, Description ="Débito"};

			Items.Add(ItemCredito);
			Items.Add(ItemDebito);

        }
    }
    
    /// <summary>
    /// DocumentosFinanceiros
    /// </summary>
    [EntityDefinitionName("DOCUMENTOSFINANCEIROS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class DocumentosFinanceiros : BusinessEntity<DocumentosFinanceiros>, IDocumentosFinanceiros
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Tipo = "TIPO";
			public const string Valor = "VALOR";
		}

        
        /// <summary>
        /// Tipo (TIPO.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public DocumentosFinanceirosTipoListaItens Tipo
        {
            get
            {
                ListItem listItem = Fields["TIPO"] as ListItem;
				if (listItem != null)
					return new DocumentosFinanceirosTipoListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["TIPO"] = new ListItem(value.Index, value.Description);
				else
					Fields["TIPO"] = null;
            }
        }
        
        /// <summary>
        /// Valor (VALOR.)
        /// Opcional = N, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo do Builder = Valor
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<decimal> Valor
        {
            get
            {
                return Fields["VALOR"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["VALOR"] = value;
            }
        }
    }
}
