//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela PESSOAS
    /// </summary>
    public partial interface IPessoas : IEntityBase
    {
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Cpf
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Nome
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Tecnologia.Common.IEntityBase PaisInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle PaisHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela PESSOAS
    /// </summary>
    public partial interface IPessoasDao : IBusinessEntityDao<IPessoas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela PESSOAS
    /// </summary>
    public partial class PessoasDao : BusinessEntityDao<Pessoas, IPessoas>, IPessoasDao
    {
        
        public static PessoasDao CreateInstance()
        {
            return CreateInstance<PessoasDao>();
        }
    }
    
    /// <summary>
    /// Pessoas
    /// </summary>
    [EntityDefinitionName("PESSOAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Pessoas : BusinessEntity<Pessoas>, IPessoas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Cpf = "CPF";
			public const string Nome = "NOME";
			public const string Pais = "PAIS";
		}

        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Cpf
        {
            get
            {
                return Fields["CPF"] as System.String;
            }
            set
            {
                Fields["CPF"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 120
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.IEntityBase PaisInstance
        {
            get
            {
                if (Pais.Handle == null)
                {
					return null;
                }
                return Pais.Instance;
            }
            set
            {
                if (value == null)
                {
					Pais = null;
					return;
                }
                Pais.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle PaisHandle
        {
            get
            {
                return Pais.Handle;
            }
            set
            {
                Pais.Handle = value;
            }
        }
        
        /// <summary>
        /// País (PAIS.)
        /// Opcional = N, Invisível = False, Pesquisar = PAISES
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation Pais
        {
            get
            {
                return Fields["PAIS"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.Pais.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.Pais.Instance = value.Instance;
                    }
                    else
                    {
                        this.Pais.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
