//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela RESERVAS
    /// </summary>
    public partial interface IReservas : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.ICarros CarroInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle CarroHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<System.DateTime> DataFim
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data início (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<System.DateTime> DataInicio
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data de Solicitação (DATASOLICITACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<System.DateTime> DataSolicitacao
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IModelosCarros ModeloCarroInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle ModeloCarroHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Observações (OBSERVACOES.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Observacoes
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IPessoas PessoaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle PessoaHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IPlanos PlanoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle PlanoHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Quilometragem (QUILOMETRAGEM.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<decimal> Quilometragem
        {
            get;
            set;
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        ReservasStatusListaItens Status
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela RESERVAS
    /// </summary>
    public partial interface IReservasDao : IBusinessEntityDao<IReservas>
    {
    }
    
    /// <summary>
    /// DAO para a tabela RESERVAS
    /// </summary>
    public partial class ReservasDao : BusinessEntityDao<Reservas, IReservas>, IReservasDao
    {
        
        public static ReservasDao CreateInstance()
        {
            return CreateInstance<ReservasDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo STATUS.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
    public class ReservasStatusListaItens : ListItems<ReservasStatusListaItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Aguardando aprovação.
        /// </summary>
        public static ReservasStatusListaItens ItemAguardandoAprovacao;
        
        /// <summary>
        /// Valor = 2, Item = Reservado.
        /// </summary>
        public static ReservasStatusListaItens ItemReservado;
        
        /// <summary>
        /// Valor = 3, Item = Recusado.
        /// </summary>
        public static ReservasStatusListaItens ItemRecusado;
        
        /// <summary>
        /// Valor = 4, Item = Devolvido.
        /// </summary>
        public static ReservasStatusListaItens ItemDevolvido;
        
        /// <summary>
        /// Valor = 5, Item = Processado.
        /// </summary>
        public static ReservasStatusListaItens ItemProcessado;
        
		public static implicit operator ReservasStatusListaItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(ReservasStatusListaItens item)
		{
			return item.Index;
		}
        
        static ReservasStatusListaItens()
        {
			ItemAguardandoAprovacao = new ReservasStatusListaItens {Index = 1, Description ="Aguardando aprovação"};
			ItemReservado = new ReservasStatusListaItens {Index = 2, Description ="Reservado"};
			ItemRecusado = new ReservasStatusListaItens {Index = 3, Description ="Recusado"};
			ItemDevolvido = new ReservasStatusListaItens {Index = 4, Description ="Devolvido"};
			ItemProcessado = new ReservasStatusListaItens {Index = 5, Description ="Processado"};

			Items.Add(ItemAguardandoAprovacao);
			Items.Add(ItemReservado);
			Items.Add(ItemRecusado);
			Items.Add(ItemDevolvido);
			Items.Add(ItemProcessado);

        }
    }
    
    /// <summary>
    /// Reservas
    /// </summary>
    [EntityDefinitionName("RESERVAS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class Reservas : BusinessEntity<Reservas>, IReservas
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Carro = "CARRO";
			public const string DataFim = "DATAFIM";
			public const string DataInicio = "DATAINICIO";
			public const string DataSolicitacao = "DATASOLICITACAO";
			public const string ModeloCarro = "MODELOCARRO";
			public const string Observacoes = "OBSERVACOES";
			public const string Pessoa = "PESSOA";
			public const string Plano = "PLANO";
			public const string Quilometragem = "QUILOMETRAGEM";
			public const string Status = "STATUS";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.ICarros CarroInstance
        {
            get
            {
                if (Carro.Handle == null)
                {
					return null;
                }
                return Carro.Instance;
            }
            set
            {
                if (value == null)
                {
					Carro = null;
					return;
                }
                Carro.Instance = (Benner.Reservas.Entidades.Carros) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle CarroHandle
        {
            get
            {
                return Carro.Handle;
            }
            set
            {
                Carro.Handle = value;
            }
        }
        
        /// <summary>
        /// Carro (CARRO.)
        /// Opcional = S, Invisível = True, Pesquisar = CARROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Carros> Carro
        {
            get
            {
                return (Fields["CARRO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Carros>(Benner.Reservas.Entidades.Carros.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Carro.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Carro.Instance = value.Instance;
                    }
                    else
                    {
                        this.Carro.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return Fields["DATAFIM"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAFIM"] = value;
            }
        }
        
        /// <summary>
        /// Data início (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return Fields["DATAINICIO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINICIO"] = value;
            }
        }
        
        /// <summary>
        /// Data de Solicitação (DATASOLICITACAO.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<System.DateTime> DataSolicitacao
        {
            get
            {
                return Fields["DATASOLICITACAO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATASOLICITACAO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IModelosCarros ModeloCarroInstance
        {
            get
            {
                if (ModeloCarro.Handle == null)
                {
					return null;
                }
                return ModeloCarro.Instance;
            }
            set
            {
                if (value == null)
                {
					ModeloCarro = null;
					return;
                }
                ModeloCarro.Instance = (Benner.Reservas.Entidades.ModelosCarros) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle ModeloCarroHandle
        {
            get
            {
                return ModeloCarro.Handle;
            }
            set
            {
                ModeloCarro.Handle = value;
            }
        }
        
        /// <summary>
        /// Modelo carro (MODELOCARRO.)
        /// Opcional = N, Invisível = False, Pesquisar = MODELOSCARROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.ModelosCarros> ModeloCarro
        {
            get
            {
                return (Fields["MODELOCARRO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.ModelosCarros>(Benner.Reservas.Entidades.ModelosCarros.Get);
            }
            set
            {
                if (value == null)
                {
                    this.ModeloCarro.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.ModeloCarro.Instance = value.Instance;
                    }
                    else
                    {
                        this.ModeloCarro.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Observações (OBSERVACOES.)
        /// Opcional = S, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Observacoes
        {
            get
            {
                return Fields["OBSERVACOES"] as System.String;
            }
            set
            {
                Fields["OBSERVACOES"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IPessoas PessoaInstance
        {
            get
            {
                if (Pessoa.Handle == null)
                {
					return null;
                }
                return Pessoa.Instance;
            }
            set
            {
                if (value == null)
                {
					Pessoa = null;
					return;
                }
                Pessoa.Instance = (Benner.Reservas.Entidades.Pessoas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle PessoaHandle
        {
            get
            {
                return Pessoa.Handle;
            }
            set
            {
                Pessoa.Handle = value;
            }
        }
        
        /// <summary>
        /// Pessoa (PESSOA.)
        /// Opcional = N, Invisível = False, Pesquisar = PESSOAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Pessoas> Pessoa
        {
            get
            {
                return (Fields["PESSOA"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Pessoas>(Benner.Reservas.Entidades.Pessoas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Pessoa.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Pessoa.Instance = value.Instance;
                    }
                    else
                    {
                        this.Pessoa.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IPlanos PlanoInstance
        {
            get
            {
                if (Plano.Handle == null)
                {
					return null;
                }
                return Plano.Instance;
            }
            set
            {
                if (value == null)
                {
					Plano = null;
					return;
                }
                Plano.Instance = (Benner.Reservas.Entidades.Planos) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle PlanoHandle
        {
            get
            {
                return Plano.Handle;
            }
            set
            {
                Plano.Handle = value;
            }
        }
        
        /// <summary>
        /// Plano (PLANO.)
        /// Opcional = N, Invisível = False, Pesquisar = PLANOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Planos> Plano
        {
            get
            {
                return (Fields["PLANO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Planos>(Benner.Reservas.Entidades.Planos.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Plano.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Plano.Instance = value.Instance;
                    }
                    else
                    {
                        this.Plano.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Quilometragem (QUILOMETRAGEM.)
        /// Opcional = S, Invisível = False, Valor Mínimo = , Valor Máximo = , Tipo no Builder = Número
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<decimal> Quilometragem
        {
            get
            {
                return Fields["QUILOMETRAGEM"] as System.Nullable<System.Decimal>;
            }
            set
            {
                Fields["QUILOMETRAGEM"] = value;
            }
        }
        
        /// <summary>
        /// Status (STATUS.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public ReservasStatusListaItens Status
        {
            get
            {
                ListItem listItem = Fields["STATUS"] as ListItem;
				if (listItem != null)
					return new ReservasStatusListaItens { Index = listItem.Value, Description = listItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["STATUS"] = new ListItem(value.Index, value.Description);
				else
					Fields["STATUS"] = null;
            }
        }
    }
}
