//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entidades
{
    
    
    /// <summary>
    /// Interface para a tabela RESERVADOCUMENTOS
    /// </summary>
    public partial interface IReservaDocumentos : IEntityBase
    {
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Tecnologia.Common.IEntityBase DocumentoFinanceiroInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle DocumentoFinanceiroHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IReservas ReservaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle ReservaHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela RESERVADOCUMENTOS
    /// </summary>
    public partial interface IReservaDocumentosDao : IBusinessEntityDao<IReservaDocumentos>
    {
    }
    
    /// <summary>
    /// DAO para a tabela RESERVADOCUMENTOS
    /// </summary>
    public partial class ReservaDocumentosDao : BusinessEntityDao<ReservaDocumentos, IReservaDocumentos>, IReservaDocumentosDao
    {
        
        public static ReservaDocumentosDao CreateInstance()
        {
            return CreateInstance<ReservaDocumentosDao>();
        }
    }
    
    /// <summary>
    /// ReservaDocumentos
    /// </summary>
    [EntityDefinitionName("RESERVADOCUMENTOS")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class ReservaDocumentos : BusinessEntity<ReservaDocumentos>, IReservaDocumentos
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string DocumentoFinanceiro = "DOCUMENTOFINANCEIRO";
			public const string Reserva = "RESERVA";
		}

        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.IEntityBase DocumentoFinanceiroInstance
        {
            get
            {
                if (DocumentoFinanceiro.Handle == null)
                {
					return null;
                }
                return DocumentoFinanceiro.Instance;
            }
            set
            {
                if (value == null)
                {
					DocumentoFinanceiro = null;
					return;
                }
                DocumentoFinanceiro.Instance = (EntityBase) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle DocumentoFinanceiroHandle
        {
            get
            {
                return DocumentoFinanceiro.Handle;
            }
            set
            {
                DocumentoFinanceiro.Handle = value;
            }
        }
        
        /// <summary>
        /// Documento financeiro (DOCUMENTOFINANCEIRO.)
        /// Opcional = N, Invisível = False, Pesquisar = DOCUMENTOSFINANCEIROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation DocumentoFinanceiro
        {
            get
            {
                return Fields["DOCUMENTOFINANCEIRO"] as Benner.Tecnologia.Common.EntityAssociation;
            }
            set
            {
                if (value == null)
                {
                    this.DocumentoFinanceiro.Handle = null;
                }
                else
                {
                    if (value.IsLoaded)
                    {
                        this.DocumentoFinanceiro.Instance = value.Instance;
                    }
                    else
                    {
                        this.DocumentoFinanceiro.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IReservas ReservaInstance
        {
            get
            {
                if (Reserva.Handle == null)
                {
					return null;
                }
                return Reserva.Instance;
            }
            set
            {
                if (value == null)
                {
					Reserva = null;
					return;
                }
                Reserva.Instance = (Benner.Reservas.Entidades.Reservas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle ReservaHandle
        {
            get
            {
                return Reserva.Handle;
            }
            set
            {
                Reserva.Handle = value;
            }
        }
        
        /// <summary>
        /// Reserva (RESERVA.)
        /// Opcional = N, Invisível = False, Pesquisar = RESERVAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Reservas> Reserva
        {
            get
            {
                return (Fields["RESERVA"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Reservas>(Benner.Reservas.Entidades.Reservas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Reserva.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Reserva.Instance = value.Instance;
                    }
                    else
                    {
                        this.Reserva.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
