//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entradas
{
    
    
    /// <summary>
    /// Interface para a tabela VT_WIZARD_PESSOA
    /// </summary>
    public partial interface IVtWizardPessoa : IEntityBase
    {
        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Cpf
        {
            get;
            set;
        }
        
        /// <summary>
        /// Email (EMAIL.)
        /// Opcional = N, Invisível = False, Tamanho = 90
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Email
        {
            get;
            set;
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 90
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string Nome
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IPessoas PessoaInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle PessoaHandle
        {
            get;
            set;
        }
        
        /// <summary>
        /// Pessoa já é cadastrada (PESSOACADASTRADA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        VtWizardPessoaPessoaJaECadastradaTabItens PessoaJaECadastrada
        {
            get;
            set;
        }
        
        /// <summary>
        /// Telefone móvel (TELEFONEMOVEL.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        string TelefoneMovel
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela VT_WIZARD_PESSOA
    /// </summary>
    public partial interface IVtWizardPessoaDao : IBusinessEntityDao<IVtWizardPessoa>
    {
    }
    
    /// <summary>
    /// DAO para a tabela VT_WIZARD_PESSOA
    /// </summary>
    public partial class VtWizardPessoaDao : BusinessEntityDao<VtWizardPessoa, IVtWizardPessoa>, IVtWizardPessoaDao
    {
        
        public static VtWizardPessoaDao CreateInstance()
        {
            return CreateInstance<VtWizardPessoaDao>();
        }
    }
    
    /// <summary>
    /// Esta classe contém os itens do campo PESSOACADASTRADA.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
    public class VtWizardPessoaPessoaJaECadastradaTabItens : TabItems<VtWizardPessoaPessoaJaECadastradaTabItens>
    {
        
        /// <summary>
        /// Valor = 1, Item = Sim.
        /// </summary>
        public static VtWizardPessoaPessoaJaECadastradaTabItens ItemSim;
        
        /// <summary>
        /// Valor = 2, Item = Não.
        /// </summary>
        public static VtWizardPessoaPessoaJaECadastradaTabItens ItemNao;
        
		public static implicit operator VtWizardPessoaPessoaJaECadastradaTabItens(int index)
		{
			return GetByIndex(index);
		}

		public static implicit operator int(VtWizardPessoaPessoaJaECadastradaTabItens item)
		{
			return item.Index;
		}
        
        static VtWizardPessoaPessoaJaECadastradaTabItens()
        {
			ItemSim = new VtWizardPessoaPessoaJaECadastradaTabItens {Index = 1, Description ="Sim"};
			ItemNao = new VtWizardPessoaPessoaJaECadastradaTabItens {Index = 2, Description ="Não"};

			Items.Add(ItemSim);
			Items.Add(ItemNao);

        }
    }
    
    /// <summary>
    /// VtWizardPessoa
    /// </summary>
    [EntityDefinitionName("VT_WIZARD_PESSOA")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class VtWizardPessoa : BusinessEntity<VtWizardPessoa>, IVtWizardPessoa
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string Cpf = "CPF";
			public const string Email = "EMAIL";
			public const string Nome = "NOME";
			public const string Pessoa = "PESSOA";
			public const string PessoaJaECadastrada = "PESSOACADASTRADA";
			public const string TelefoneMovel = "TELEFONEMOVEL";
		}

        
        /// <summary>
        /// Cpf (CPF.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Cpf
        {
            get
            {
                return Fields["CPF"] as System.String;
            }
            set
            {
                Fields["CPF"] = value;
            }
        }
        
        /// <summary>
        /// Email (EMAIL.)
        /// Opcional = N, Invisível = False, Tamanho = 90
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Email
        {
            get
            {
                return Fields["EMAIL"] as System.String;
            }
            set
            {
                Fields["EMAIL"] = value;
            }
        }
        
        /// <summary>
        /// Nome (NOME.)
        /// Opcional = N, Invisível = False, Tamanho = 90
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string Nome
        {
            get
            {
                return Fields["NOME"] as System.String;
            }
            set
            {
                Fields["NOME"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IPessoas PessoaInstance
        {
            get
            {
                if (Pessoa.Handle == null)
                {
					return null;
                }
                return Pessoa.Instance;
            }
            set
            {
                if (value == null)
                {
					Pessoa = null;
					return;
                }
                Pessoa.Instance = (Benner.Reservas.Entidades.Pessoas) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle PessoaHandle
        {
            get
            {
                return Pessoa.Handle;
            }
            set
            {
                Pessoa.Handle = value;
            }
        }
        
        /// <summary>
        /// Pessoa (PESSOA.)
        /// Opcional = N, Invisível = False, Pesquisar = PESSOAS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Pessoas> Pessoa
        {
            get
            {
                return (Fields["PESSOA"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Pessoas>(Benner.Reservas.Entidades.Pessoas.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Pessoa.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Pessoa.Instance = value.Instance;
                    }
                    else
                    {
                        this.Pessoa.Handle = value.Handle;
                    }
                }
            }
        }
        
        /// <summary>
        /// Pessoa já é cadastrada (PESSOACADASTRADA.)
        /// Opcional = N, Invisível = False
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public VtWizardPessoaPessoaJaECadastradaTabItens PessoaJaECadastrada
        {
            get
            {
                TabItem tabItem = Fields["PESSOACADASTRADA"] as TabItem;
				if (tabItem != null)
					return new VtWizardPessoaPessoaJaECadastradaTabItens { Index = tabItem.Value, Description = tabItem.Text };
				return null;
            }
            set
            {
                if (value != null)
					Fields["PESSOACADASTRADA"] = new TabItem(value.Index, value.Description);
				else
					Fields["PESSOACADASTRADA"] = null;
            }
        }
        
        /// <summary>
        /// Telefone móvel (TELEFONEMOVEL.)
        /// Opcional = N, Invisível = False, Tamanho = 14
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public string TelefoneMovel
        {
            get
            {
                return Fields["TELEFONEMOVEL"] as System.String;
            }
            set
            {
                Fields["TELEFONEMOVEL"] = value;
            }
        }
    }
}
