//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using Benner.Tecnologia.Business;
using Benner.Tecnologia.Common;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;


namespace Benner.Reservas.Entradas
{
    
    
    /// <summary>
    /// Interface para a tabela VT_WIZARD_RESERVA
    /// </summary>
    public partial interface IVtWizardReserva : IEntityBase
    {
        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<System.DateTime> DataFim
        {
            get;
            set;
        }
        
        /// <summary>
        /// Data início (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        System.Nullable<System.DateTime> DataInicio
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IModelosCarros ModeloCarroInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle ModeloCarroHandle
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Benner.Reservas.Entidades.IPlanos PlanoInstance
        {
            get;
            set;
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        Handle PlanoHandle
        {
            get;
            set;
        }
    }
    
    /// <summary>
    /// Interface para o DAO para a tabela VT_WIZARD_RESERVA
    /// </summary>
    public partial interface IVtWizardReservaDao : IBusinessEntityDao<IVtWizardReserva>
    {
    }
    
    /// <summary>
    /// DAO para a tabela VT_WIZARD_RESERVA
    /// </summary>
    public partial class VtWizardReservaDao : BusinessEntityDao<VtWizardReserva, IVtWizardReserva>, IVtWizardReservaDao
    {
        
        public static VtWizardReservaDao CreateInstance()
        {
            return CreateInstance<VtWizardReservaDao>();
        }
    }
    
    /// <summary>
    /// VtWizardReserva
    /// </summary>
    [EntityDefinitionName("VT_WIZARD_RESERVA")]
    [DataContract(Namespace = "http://Benner.Tecnologia.Common.DataContracts/2007/09", Name = "EntityBase")]
    public partial class VtWizardReserva : BusinessEntity<VtWizardReserva>, IVtWizardReserva
    {
        
        /// <summary>
        /// Possui constantes para retornarem o nome dos campos definidos no Builder para cada propriedade
        /// </summary>
		public static class FieldNames
		{
			public const string DataFim = "DATAFIM";
			public const string DataInicio = "DATAINICIO";
			public const string ModeloCarro = "MODELOCARRO";
			public const string Plano = "PLANO";
		}

        
        /// <summary>
        /// Data fim (DATAFIM.)
        /// Opcional = S, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<System.DateTime> DataFim
        {
            get
            {
                return Fields["DATAFIM"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAFIM"] = value;
            }
        }
        
        /// <summary>
        /// Data início (DATAINICIO.)
        /// Opcional = N, Invisível = False, Formato Data = Dia, Mês, Ano - Formato Hora = Hora, Minuto
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public System.Nullable<System.DateTime> DataInicio
        {
            get
            {
                return Fields["DATAINICIO"] as System.Nullable<System.DateTime>;
            }
            set
            {
                Fields["DATAINICIO"] = value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IModelosCarros ModeloCarroInstance
        {
            get
            {
                if (ModeloCarro.Handle == null)
                {
					return null;
                }
                return ModeloCarro.Instance;
            }
            set
            {
                if (value == null)
                {
					ModeloCarro = null;
					return;
                }
                ModeloCarro.Instance = (Benner.Reservas.Entidades.ModelosCarros) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle ModeloCarroHandle
        {
            get
            {
                return ModeloCarro.Handle;
            }
            set
            {
                ModeloCarro.Handle = value;
            }
        }
        
        /// <summary>
        /// Modelo carro (MODELOCARRO.)
        /// Opcional = N, Invisível = False, Pesquisar = MODELOSCARROS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.ModelosCarros> ModeloCarro
        {
            get
            {
                return (Fields["MODELOCARRO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.ModelosCarros>(Benner.Reservas.Entidades.ModelosCarros.Get);
            }
            set
            {
                if (value == null)
                {
                    this.ModeloCarro.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.ModeloCarro.Instance = value.Instance;
                    }
                    else
                    {
                        this.ModeloCarro.Handle = value.Handle;
                    }
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Reservas.Entidades.IPlanos PlanoInstance
        {
            get
            {
                if (Plano.Handle == null)
                {
					return null;
                }
                return Plano.Instance;
            }
            set
            {
                if (value == null)
                {
					Plano = null;
					return;
                }
                Plano.Instance = (Benner.Reservas.Entidades.Planos) value;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Handle PlanoHandle
        {
            get
            {
                return Plano.Handle;
            }
            set
            {
                Plano.Handle = value;
            }
        }
        
        /// <summary>
        /// Plano (PLANO.)
        /// Opcional = N, Invisível = False, Pesquisar = PLANOS
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("BEF Code Generator", "22.0.36.3")]
        public Benner.Tecnologia.Common.EntityAssociation<Benner.Reservas.Entidades.Planos> Plano
        {
            get
            {
                return (Fields["PLANO"] as EntityAssociation).Wrap<Benner.Reservas.Entidades.Planos>(Benner.Reservas.Entidades.Planos.Get);
            }
            set
            {
                if (value == null)
                {
                    this.Plano.Handle = null;
                }
                else
                {
                    if (value.Association.IsLoaded)
                    {
                        this.Plano.Instance = value.Instance;
                    }
                    else
                    {
                        this.Plano.Handle = value.Handle;
                    }
                }
            }
        }
    }
}
