<%@ Page Title="Monitor de Processos" Language="C#" Inherits="Benner.Tecnologia.Wes.Components.WebApp.WesPage" %>
   
<%@ Register Assembly="Benner.Tecnologia.Wes.Components.WebApp" Namespace="Benner.Tecnologia.Wes.Components.WebApp" TagPrefix="wes" %>
<%@ Register Assembly="Benner.Tecnologia.Wes.Components" Namespace="Benner.Tecnologia.Wes.Components" TagPrefix="wes" %>
     
      <asp:Content ID="Content1" ContentPlaceHolderID="Main" Runat="Server">
    <div class="row">
        <wes:FilterWidget runat="server" ID="FILTRO" Title="Filtro" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="Z_PROCESSOS.GRID" DefaultFilterName="Processos de hoje" Mode="Selectable" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="62"  />
        <wes:Tile runat="server" ID="PENDENTES" Title="Pendentes" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="Z_PROCESSOS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.SITUACAO = 6 OR A.SITUACAO = 1" CommandName="CMD_TILE" Value="NOME" Description="Pendentes/Executando" Icon="fa fa-clock-o" Color="grey-cascade" ValueAggregation="Count" TileType="Default" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="125"  />
        <wes:Tile runat="server" ID="SUCESSO" Title="Sucesso" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="Z_PROCESSOS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.SITUACAO = 5" CommandName="CMD_TILE" Value="NOME" Description="Sucesso" Icon="fa fa-check" Color="green-meadow" ValueAggregation="Count" TileType="Default" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="150"  />
        <wes:Tile runat="server" ID="ERROS" Title="Erros" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="Z_PROCESSOS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.SITUACAO = 4" CommandName="CMD_TILE" Value="NOME" Description="Erros" Icon="fa fa-warning" Color="red" ValueAggregation="Count" TileType="Default" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="162"  />
        <wes:Tile runat="server" ID="CANCELADOS" Title="Cancelados" Subtitle="" PortletCssClass="" PortletLayout="None" BootstrapCols="3" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="Z_PROCESSOS.GRID" CompanyFilterMode="OnlyCompany" CriteriaWhereClause="A.SITUACAO = 2 OR A.SITUACAO = 3" CommandName="CMD_TILE" Value="NOME" Description="Cancelando/Cancelados" Icon="fa fa-times" Color="yellow" ValueAggregation="Count" TileType="Default" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="202"  />
        <wes:AmCharts runat="server" ID="PROCESSOSQUEMAISEXECUTARAM" Title="Processos que mais executaram" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="ZPROCESSOS_EXECUCOES.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CommandName="CMD_DETALHES" ChartType="Bar" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJwcm9jZXNzbyIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImJhbGxvblRleHQiOiJbW2NhdGVnb3J5XV0gOiBbW3ZhbHVlXV0iLCJsYWJlbFRleHQiOiIiLCJpZCI6InNlcmllLTE1NjYyMjM1MDg5NjciLCJ0aXRsZSI6IkNvbSBzdWNlc3NvIiwidmFsdWVGaWVsZCI6ImNvbXN1Y2Vzc28iLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInR5cGUiOiJjb2x1bW4iLCJidWxsZXQiOm51bGwsImxpbmVBbHBoYSI6MCwiZmlsbEFscGhhcyI6MSwiZmlsbENvbG9ycyI6IiMxYmJjOWIiLCJsaW5lQ29sb3IiOiIjMWJiYzliIiwiYnVsbGV0Q29sb3IiOiIjMWJiYzliIn0seyJiYWxsb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwibGFiZWxUZXh0IjoiIiwiaWQiOiJzZXJpZS0xNTY2MjIzNDY5MDI0IiwidGl0bGUiOiJDb20gZXJybyIsInZhbHVlRmllbGQiOiJjb21lcnJvIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoiY29sdW1uIiwiYnVsbGV0IjpudWxsLCJsaW5lQWxwaGEiOjAsImZpbGxBbHBoYXMiOjEsImZpbGxDb2xvcnMiOiIjZTc1MDVhIiwibGluZUNvbG9yIjoiI2U3NTA1YSIsImJ1bGxldENvbG9yIjoiI2U3NTA1YSJ9LHsiYmFsbG9uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImxhYmVsVGV4dCI6IiIsImlkIjoic2VyaWUtMTU2NjIyMzU2MzU2NSIsInRpdGxlIjoiUGVuZGVudGVzL0V4ZWN1dGFudG8iLCJ2YWx1ZUZpZWxkIjoicGVuZGVudGVzIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoiY29sdW1uIiwiYnVsbGV0IjpudWxsLCJsaW5lQWxwaGEiOjAsImZpbGxBbHBoYXMiOjEsImZpbGxDb2xvcnMiOiIjOTVhNWE2IiwibGluZUNvbG9yIjoiIzk1YTVhNiIsImJ1bGxldENvbG9yIjoiIzk1YTVhNiJ9LHsiYmFsbG9uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImxhYmVsVGV4dCI6IiIsImlkIjoic2VyaWUtMTU2NjMxMDM5OTE2MyIsInRpdGxlIjoiQ2FuY2VsYW5kby9DYW5jZWxhZG9zIiwidmFsdWVGaWVsZCI6ImNhbmNlbGFkb3MiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInR5cGUiOiJjb2x1bW4iLCJidWxsZXQiOm51bGwsImxpbmVBbHBoYSI6MCwiZmlsbEFscGhhcyI6MSwiZmlsbENvbG9ycyI6IiNjNDlmNDciLCJsaW5lQ29sb3IiOiIjYzQ5ZjQ3IiwiYnVsbGV0Q29sb3IiOiIjYzQ5ZjQ3In1dLCJ2YWx1ZUF4ZXMiOlt7ImlkIjoiVmFsdWVBeGlzLTEiLCJ0aXRsZSI6IiIsInN0YWNrVHlwZSI6InJlZ3VsYXIifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJwb3NpdGlvbiI6ImJvdHRvbSIsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9LCJyb3RhdGUiOnRydWV9" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="242"  />
        <wes:AmCharts runat="server" ID="PROCESSOSQUEGASTARAMMAISTEMPO" Title="Processos que gastaram mais tempo de CPU" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="6" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="ZPROCESSOS_DURACAO.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CommandName="CMD_DETALHES" ChartType="Bar" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJwcm9jZXNzbyIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImxhYmVsVGV4dCI6IiIsImJhbGxvb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwiaWQiOiJBbUdyYXBoLTEiLCJ0aXRsZSI6IlRlbXBvIENQVSIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidmFsdWVGaWVsZCI6InRlbXBvX2NwdSIsInR5cGUiOiJjb2x1bW4iLCJmaWxsQWxwaGFzIjoxLCJmaWxsQ29sb3JzIjoiIzM1OThkYyIsImxpbmVDb2xvciI6IiMzNTk4ZGMiLCJidWxsZXRDb2xvciI6IiMzNTk4ZGMifV0sInZhbHVlQXhlcyI6W3siaWQiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiVGVtcG8gZW0gc2VndW5kb3MifV0sImxlZ2VuZCI6eyJlbmFibGVkIjp0cnVlLCJwb3NpdGlvbiI6ImJvdHRvbSIsInVzZUdyYXBoU2V0dGluZ3MiOnRydWV9LCJyb3RhdGUiOnRydWV9" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="282"  />
        <wes:AmCharts runat="server" ID="SERVIDORES" Title="Tipos de processos por servidor" Subtitle="" PortletCssClass="" PortletLayout="Default" BootstrapCols="12" FontIcon="" ShowTitle="true" ProviderWidgetUniqueId="FILTRO" ChromeState="Normal" CanDelete="True" CanUpdate="True" CanInsert="True" EntityViewName="ZPROCESSOS_SERVIDORES.DATASOURCE.GRID" Mode="None" CompanyFilterMode="OnlyCompany" CommandName="CMD_SERVIDORES" ChartType="Column" ChartHeight="400" ChartDefinition="eyJ0eXBlIjoic2VyaWFsIiwibGFuZ3VhZ2UiOiJwdCIsInRoZW1lIjoibGlnaHQiLCJleHBvcnQiOnsiZW5hYmxlZCI6dHJ1ZX0sImNhdGVnb3J5RmllbGQiOiJzZXJ2aWRvciIsInN0YXJ0RHVyYXRpb24iOjEsImNhdGVnb3J5QXhpcyI6eyJncmlkUG9zaXRpb24iOiJzdGFydCJ9LCJncmFwaHMiOlt7ImJhbGxvblRleHQiOiJbW2NhdGVnb3J5XV0gOiBbW3ZhbHVlXV0iLCJsYWJlbFRleHQiOiIiLCJpZCI6InNlcmllLTE1NjQ3NzU5NTMwNzQiLCJ0aXRsZSI6IkFnZW5kYW1lbnRvcyIsInZhbHVlRmllbGQiOiJhZ2VuZGFtZW50b3MiLCJhbHBoYUZpZWxkIjoiZmlsbF9hbHBoYV9maWVsZCIsInR5cGUiOiJjb2x1bW4iLCJidWxsZXQiOm51bGwsImxpbmVBbHBoYSI6MCwiZmlsbEFscGhhcyI6MSwiZmlsbENvbG9ycyI6IiMzNTk4ZGMiLCJsaW5lQ29sb3IiOiIjMzU5OGRjIiwiYnVsbGV0Q29sb3IiOiIjMzU5OGRjIn0seyJiYWxsb25UZXh0IjoiW1tjYXRlZ29yeV1dIDogW1t2YWx1ZV1dIiwibGFiZWxUZXh0IjoiIiwiaWQiOiJzZXJpZS0xNTY0Nzc1OTY3NjU5IiwidGl0bGUiOiJCVEwiLCJ2YWx1ZUZpZWxkIjoiYnRsIiwiYWxwaGFGaWVsZCI6ImZpbGxfYWxwaGFfZmllbGQiLCJ0eXBlIjoiY29sdW1uIiwiYnVsbGV0IjpudWxsLCJsaW5lQWxwaGEiOjAsImZpbGxBbHBoYXMiOjEsImZpbGxDb2xvcnMiOiIjOWI1OWI2IiwibGluZUNvbG9yIjoiIzliNTliNiIsImJ1bGxldENvbG9yIjoiIzliNTliNiJ9LHsiYmFsbG9uVGV4dCI6IltbY2F0ZWdvcnldXSA6IFtbdmFsdWVdXSIsImxhYmVsVGV4dCI6IiIsImlkIjoic2VyaWUtMTU2NDc3NjkzOTQ5OSIsInRpdGxlIjoiT3V0cm9zIiwidmFsdWVGaWVsZCI6Im91dHJvcyIsImFscGhhRmllbGQiOiJmaWxsX2FscGhhX2ZpZWxkIiwidHlwZSI6ImNvbHVtbiIsImJ1bGxldCI6bnVsbCwibGluZUFscGhhIjowLCJmaWxsQWxwaGFzIjoxLCJmaWxsQ29sb3JzIjoiIzMyYzVkMiIsImxpbmVDb2xvciI6IiMzMmM1ZDIiLCJidWxsZXRDb2xvciI6IiMzMmM1ZDIifV0sInZhbHVlQXhlcyI6W3siaWQiOiJWYWx1ZUF4aXMtMSIsInRpdGxlIjoiIiwic3RhY2tUeXBlIjoicmVndWxhciJ9XSwibGVnZW5kIjp7ImVuYWJsZWQiOnRydWUsInBvc2l0aW9uIjoiYm90dG9tIiwidXNlR3JhcGhTZXR0aW5ncyI6dHJ1ZX0sInJvdGF0ZSI6ZmFsc2V9" PageId="SITESETTINGS_PROCESSES_DASHBOARD" Level="15" Order="362"  />
        </div>
    
        <style>
              .filter-search-form{
    margin-bottom: 15px !important;
}

              </style>
      </asp:Content>
    